# Generated by Django 5.1.1 on 2024-09-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodprocess",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="processes",
                to="food.food",
            ),
        ),
    ]
