# Generated by Django 5.1.1 on 2024-09-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("line", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodProcessLineStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="name"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "line",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="steps",
                        to="line.foodprocessline",
                    ),
                ),
                (
                    "next_step",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="step.foodprocesslinestep",
                    ),
                ),
            ],
            options={
                "db_table": "food_process_line_step",
            },
        ),
    ]
