# Generated by Django 5.1.1 on 2024-09-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodprocesslinestep",
            name="step_yield",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="yield"),
        ),
    ]
