# Generated by Django 5.1.1 on 2024-09-19 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodprocesslinestep",
            name="next_step",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="step.foodprocesslinestep",
            ),
        ),
    ]
