# Generated by Django 5.1.1 on 2024-09-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0002_foodprocesslinestep_step_yield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodprocesslinestep",
            name="step_yield",
            field=models.FloatField(default=100, verbose_name="yield"),
        ),
    ]
