# Generated by Django 5.1.1 on 2024-09-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step", "0002_alter_foodprocesslinestep_next_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodprocesslinestep",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="enabled"),
        ),
    ]
